# ==============================================================================
# PIPELINE EXECUTION TRIGGERS
# ==============================================================================
hyperparameters:
  lr: 1e-4
  aggregation_epochs: 60
  batch_size: 64
  num_classes: 2
  architecture: "resnet"
  num_pipelines: 25
  task: "pipelines" # Options: "preprocess", "pipelines"
  

# ==============================================================================
# DATALOADERS PARAMETERS
# ==============================================================================
dataloaders:
  num_workers: 4
  cache_rate: 1.0

# ==============================================================================
# GLOBAL I/O DIRECTORIES
# ==============================================================================
io_dirs:
  save_model_dir: "/home/nfferreira/data/model/"
  dicom_root_LIGA: "/home/nfferreira/LIGA/dicom"
  dicom_root_DDSM: "/home/nfferreira/DDSM/CBIS-DDSM"
  dicom_root_VINDR: "/home/nfferreira/VinDr/images"
  #dataset_dict:
  #  "/home/nfferreira/data/dataset_DDSM.json": "DDSM"
  #  "/home/nfferreira/data/dataset_Planmed.json": "PLANMED"
  #  "/home/nfferreira/data/dataset_IMS.json": "IMS"
  #  "/home/nfferreira/data/dataset_SIEMENS.json": "SIEMENS"
  #  "/home/nfferreira/data/dataset_VINDR_DDSM.json": "VINDR-DDSM"
  #  "/home/nfferreira/data/dataset_VINDR_ALL.json": "VINDR"

  dataset_list:
    - "data/datasets/dataset_DDSM.json"
    - "data/datasets/dataset_Planmed.json"
    - "data/datasets/dataset_IMS.json"
    - "data/datasets/dataset_SIEMENS.json"
    - "data/datasets/dataset_VINDR_DDSM.json"
    - "data/datasets/dataset_VINDR_ALL.json"
  kfold_ddsm:
    - "data/datasets/ddsm-kfolds/dataset_site-0_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-1_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-2_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-3_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-4_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-5_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-6_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-7_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-8_DDSM_KFOLD.json"
    - "data/datasets/ddsm-kfolds/dataset_site-9_DDSM_KFOLD.json"
  preprocess_prefix: "data/preprocessed/"